[package]
name = "pleaser"
version = "0.3.0"
authors = ["ed neville <ed@s5h.net>"]
edition = "2018"
description = "please, a polite sudo alternative"
license = "GPL-3.0-or-later"
homepage = "https://www.usenix.org.uk/content/please.html"
repository = "https://gitlab.com/edneville/please"


[dependencies]
regex = "1.3.9"
chrono = "0.4.15"
getopt = "1.0.1"
nix = "0.14.1"
pam = "0.7.0"
users = "0.8.1"
rpassword = "3.0.2"
syslog= "5.0.0"
libc = "0.2.74"
rust-ini = "0.14.0"
