[package]
name = "please"
version = "0.1.0"
authors = ["ed neville <ed@s5h.net>"]
edition = "2018"

[dependencies]
regex = "*"
chrono = "*"
getopt = "*"
nix = "0.14.1"
pam = "*"
users = "*"
rpassword = "3.0.2"
